export const ADD_PLAYER = "ADD_PLAYER";
export const REMOVE_PLAYER = "REMOVE_PLAYER";

export const SET_GAME = "SET_GAME";

export const SET_GAME_STATUS_START = "SET_GAME_STATUS_START";
export const SET_GAME_STATUS_END = "SET_GAME_STATUS_END";
export const CLEAR_GAME_STATUSES = "CLEAR_GAME_STATUSES";

export const REMOVE_POINTS_FROM_PLAYERS = "REMOVE_POINTS_FROM_PLAYERS";
