export const ADD_PLAYER = "ADD_PLAYER";
export const REMOVE_PLAYER = "REMOVE_PLAYER";

export const SET_GAME = "SET_GAME";

export const REMOVE_POINTS_FROM_PLAYERS = "REMOVE_POINTS_FROM_PLAYERS";

export const SET_STATUS_GAME_GOES = "SET_STATUS_GAME_GOES";
export const SET_STATUS_GAME_STOPS = "SET_STATUS_GAME_STOPS";
export const SET_STATUS_GAME_ENDS = "SET_STATUS_GAME_ENDS";
